### ISSUE TITLE
Toggle which cards appear in Baseline diet page

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#301] opened 2021-02-28 11:04 UTC
# Summary

Dependent on the data available, not all of the card/charts are valid.  The **baseline** page can either be displaying data as: **"Household level"** or **"country level"**. 

 In **'household' level** mode, the **4 existing cards** should be displayed:

* "Map View"
* "Top 20 Food Items" 
* "Household Dietary Supply"
* "Monthly Food"

For **country level** it should be only the **first 2**:
* "Map View"
*  "Top 20 Food items"

Future cards may appear in one or other mode.

The mode will also impact which API endpoints each card should access

# Details

Exact methods and level of abstraction/encapsulation of 'mode' and config for which cards are visible/cards API endpoints is open for discussion.  

# Wireframes

Suggested wireframes. Not reviewed by Andy yet.

The data level could be displayed on the summary card.

Household:

![household](https://user-images.githubusercontent.com/72566636/109631351-c697f100-7b3d-11eb-8a44-af8cb5e316da.png)

Country:

![country](https://user-images.githubusercontent.com/72566636/109631377-cb5ca500-7b3d-11eb-9241-d299008cb0d3.png)

# Acceptance Criteria

- [x] Diet pages contain a state flag to indicate if in 'household' or 'country' level mode
- [x] Individual cards can be displayed or not displayed dependent on mode
- [x] Household supply and Monthly food cards only appear if in household mode
- [ ] API endpoint used by card for data can differ dependent on which mode the page is displaying
- [x] Mode flag can be set from dietary sources API endpoint (TBC)

**Comment by Fuhji** [comment] 2021-03-02 11:31
@bgsandan is this extra data level only shown in Baseline page?

**Comment by Fuhji** [comment] 2021-03-02 11:48
Is there a plan to have the API endpoint in place before the feature freeze @bgsandan ?

**Comment by bgsandan** [comment] 2021-03-02 11:56
@Fuhji - Yes, only in baseline page makes sense actually

Re: API - Yes, plan is later today and/or pre-stand-up tomorrow :)

**Comment by jon571** [comment] 2021-03-03 08:39
Have you finished with this area now @Fuhji ?  I've just put this select in on the baseline description component (on my branch).

**Comment by Fuhji** [comment] 2021-03-03 08:41
The issue is blocked and can't be completed until the API is in place, see https://github.com/micronutrientsupport/micronutrient-support-tool/issues/301#issuecomment-788856288

**Comment by jon571** [comment] 2021-03-03 09:11
I'll try to get my stuff in this morning, but it pretty much finishes this task off apart from getting the allowed options from a real api.  It currently hard-codes them in the MicronutrientDataOption object.

**Comment by jon571** [comment] 2021-03-03 11:12
I missed the bit (or failed to realize the implications) when the select was removed :-(
Oh well, if it is selectable in the future, a select will appear.

**Comment by bgsandan** [comment] 2021-03-03 11:37
Development API now should support this data

**Comment by jon571** [comment] 2021-03-03 12:49
@bgsandan is it worth leaving the select code in?  It won't show unless there is are options.  If it will never happed though I might as well clean it out.

**Comment by bgsandan** [comment] 2021-03-03 14:10
@jon571 Sorry, just to clarify what do you mean by the select code?  Are we talking about the Micronutrient data options select box?  If so, very happy for it to remain visually/functionally exactly as it is.  The one option that is currently auto filled from the dummy json can come from the API `/data-sources` route.  In Quick MAPS it will still not be selectable, but in future modes it could/will be.

Does that answer the question or have I misunderstood?

**Comment by jon571** [comment] 2021-03-03 14:27
That is what I meant @bgsandan :-)

Cheers.

**Comment by jon571** [comment] 2021-03-10 15:26
I believe this issue is complete.

**Comment by jon571** [comment] 2021-03-11 10:15
Will be complete after #365 merged

**Closed** 2021-03-11 10:18 UTC
